
base:
  project_name: ALMT_Demo_SIMS
  ckpt_root: ./ckpt
  seed: 0
  lr: 0.00001
  weight_decay: 0.0002
  batch_size: 64
  n_epochs: 40
  num_workers: 8
  gpu_id: 0
dataset:
  datasetName: sims
  dataPath: /mnt/e/clfe/sims_v2_s_unaligned.pkl
  train_mode: regression
model:
  bert_pretrained: bert-base-chinese
  l_input_dim: 768
  a_input_dim: 25
  v_input_dim: 177
  l_proj_dst_dim: 128
  a_proj_dst_dim: 128
  v_proj_dst_dim: 128
  token_len: 8
  token_dim: 128
  l_input_length: 50
  a_input_length: 925
  v_input_length: 232
  proj_input_dim: 128
  proj_depth: 1
  proj_heads: 8
  proj_mlp_dim: 128
  token_length: 8
  l_enc_heads: 8
  l_enc_mlp_dim: 128
  AHL_depth: 3
  ahl_heads: 8
  ahl_dim_head: 16
  ahl_droup: 0.15
  fusion_heads: 8
  fusion_mlp_dim: 128
  fusion_layer_depth: 4
